# Generated by Django 6.0.4 on 2026-05-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stock',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
