# Generated by Django 6.0.4 on 2026-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash on Delivery'), ('TALABAT_PAY', 'Talabat Pay (Wallet)'), ('CREDIT_CARD', 'Credit Card'), ('POSTPAID', 'PostPaid (Pay Later)')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
    ]
